# Generated by Django 4.0.5 on 2022-06-26 13:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='discount',
            name='date_until',
            field=models.DateField(),
        ),
    ]
