# Generated by Django 4.0.5 on 2022-06-26 14:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_alter_discount_date_until'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='lesson',
            options={'ordering': ['priority']},
        ),
    ]
